baseurl = "http://www.mugairyu.fr"
title = "Mugai Ryu - école traditionnelle de sabre"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]
googleAnalytics = "UA-123-45"

[params]
  description = '<!--[-->無外真伝無外流居合兵道<!--]--><br />
                <!--[-->Mugai-ryu Iai hyôdô<!--]--><br />
                <!--[-->école traditionnelle de sabre Japonais<!--]-->'
  logoimage = "/images/logo.png"
  copyright = "Mugai-ryu France"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/musasinokuni.mugaikai/"

[menu]
  [[menu.mainmenu]]
  identifier = "mugairyu"
  name = "Mugairyu"
  url = "/mugairyu/"
  weight = 1

  [[menu.mainmenu]]
  identifier = "media"
  name = "Média"
  url = "/media/"
  weight = 2

  [[menu.mainmenu]]
  identifier = "france"
  name = "France"
  url = "/france/"
  weight = 3

  [[menu.mainmenu]]
  identifier = "japon"
  name = "Japon"
  url = "/japon/"
  weight = 4

  [[menu.mainmenu]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5

[languages]
[languages.fr]
languageName = "French"
weight = 1
title = "Mugai Ryu"
