baseurl = "http://www.mugairyu.fr"
title = "Mugai Ryu - école traditionnelle de sabre"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->無外真伝無外流居合兵道<!--]--><br />
                <!--[-->Mugai-ryu Iai hyôdô<!--]--><br />
                <!--[-->école traditionnelle de sabre Japonais<!--]-->'
  logoimage = "/images/logo.png"
  copyright = "Mugai-ryu France"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/musasinokuni.mugaikai/"

sectionPagesMenu = "main"


[languages]
[languages.fr]
languageName = "French"
weight = 1
title = "Mugai Ryu"
