baseurl = "http://www.mugairyu.fr"
title = "Mugai Ryu - école traditionnelle de sabre"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->無外真伝無外流居合兵道<br /> Mugai-ryu Iai hyôdô<!--]--><br />'
  logoimage = "/images/logo.png"
  copyright = "Mugai-ryu France"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.fr]
languageName = "French"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
